### ISSUE TITLE
jump in operator-pending-mode?

### ISSUE THREAD

**Issue by lilydjwg** [monkoose/vim9-stargate#11]
E.g. `d<stargate>` deletes from current to chosen destination.

**Comment by monkoose** [comment]
It should already work. But with some inconsistency same as regular search `d/pattern` backward it would include position and forward it would delete till position. Maybe i would fix this in the future, but it would require some non-trivial changes.

Have your read documentation? You should add `map` or `noremap` (it is not nnoremap with two n) for working in normal, visual and operator pending modes.

**Comment by lilydjwg** [comment]
Yes, I'm using `noremap`:

```
noremap <M-q>f <Cmd>call stargate#OKvim(1)<CR>
```

It seems that it only works with `<leader>f` (`\f`), not `<M-q>f` or `<C-a>f` or `sf`. `<M-q>f` worked with easymotion.

**Comment by monkoose** [comment]
`noremap <M-q>f <Cmd>call stargate#OKvim(1)<CR>` - doesn't work for me either, but it is because i wasn't able to make `<M-..>` to work in my configs for my terminal. But `noremap ^[qf <Cmd>call stargate#OKvim(1)<CR>` does work as expected for me (to make `Alt-q f` keybinding to start stargate in operator-pending mode). `^[q` is `C-v-Esc q` if you type it in command line.

Other non alt keybindings work for me.

This plugin doesn't change any behavior how vim maps work. 
Can you test something like `noremap <M-q>f <Cmd>echo 'hello'<CR>` outputs hello in echo area in operator pending mode?

**Comment by lilydjwg** [comment]
It seems to be a gvim bug. I've filed an issue for vim: https://github.com/vim/vim/issues/11061
